import 'task.dart';

/// Represents a scheduling suggestion generated by the adaptive scheduling system.
class Suggestion {
  final Task task;
  final DateTime suggestedStartTime;
  final DateTime suggestedEndTime;
  final SuggestionType type;
  final String reason; // Why this suggestion was made
  final double confidence; // 0.0 to 1.0

  Suggestion({
    required this.task,
    required this.suggestedStartTime,
    required this.suggestedEndTime,
    required this.type,
    required this.reason,
    this.confidence = 0.5,
  });

  Duration get duration => suggestedEndTime.difference(suggestedStartTime);
}

enum SuggestionType {
  heavyTask, // Deep work task during high-focus window
  lightTask, // Light task during low-focus window
  collaboration, // Task that might benefit from collaboration
  urgent, // Task with approaching due date
}